CONTENT_AREA = {
    "auto2000.co.id": "tips-detail-content",
    "ahrefs": "post-content",
    "allianz": "text",
    "carmudi": "single-entry-summary-post-content",
    "duitpintar": "blog-post_content",
    "doktermobil": "elementor-widget-container",
    "gridoto": "read__article",
    "idntimes": "content-post-description full",
    "kompas": "read__header col-offset-fluid clearfix",
    "lifepal": "content.SinglePost_post__content__3RMzn",
    "mobbi": "article-details-content",
    "otoklix": "post-content",
    "qoala": "post-content",
}
