

media_o = "https://docs.google.com/spreadsheets/d/1m-BkjuRaFooBW5rpbT3Woy0otg7ghWww6p5Qn671xrM/edit#gid=0"
s_robot = "https://docs.google.com/spreadsheets/d/1iP4bmd09YZiszeyGNp6ei9ETmcY3HmrPHYLIAjCd1qg/edit#gid=0"